### ISSUE TITLE
デプロイする際にやったことをまとめ、スクリプトを作成する。

### ISSUE THREAD

**Issue by ogaogs** [AyumuOgasawara/receipt-scanner-infra#4]
## 概要
`terraform apply`後にpostgresのインストールや、next、pythonの設定など、いろいろやることがある。

それを自動化するためのスクリプトを作成したい。

**Comment by ogaogs** [comment]
## 接続してからのやったこと

### DBの設定
``` sh
# 必要な依存パッケージをインストール
sudo apt-get update
sudo apt-get install -y wget ca-certificates

# PostgreSQLのGPGキーを追加
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# PostgreSQLのリポジトリを追加
echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

# パッケージリストを更新
sudo apt-get update

# PostgreSQL 16をインストール
sudo apt-get install -y postgresql-16

# インストールの確認
psql --version
```

### アプリのディレクトリ作成
``` sh
mkdir recipt-scanner
cd recipt-scanner
mkdir next
mkdir python
```

## ファイルの同期
``` sh
rsync -avz --delete \
  -e "ssh -i キーのファイル" \ 
  .next/ \
  public/ \
  package.json \
  package-lock.json \
  <EC2ユーザー名>@<EC2_IPアドレス>:/home/ubuntu/recipt-scanner/next
```

## nodeの環境構築
``` sh
# node 22でローカルの環境と合わせる
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
sudo apt-get install -y nodejs
node -v
npm -v

## 削除方法
sudo apt purge --autoremove nodejs npm
sudo rm -rf /usr/bin/node /usr/bin/npm
sudo apt-get clean
```

**Comment by ogaogs** [comment]
nginxを設定して、Nextの前に噛ませる

## nginxのインストール
``` sh
sudo apt-get install -y nginx
sudo systemctl start nginx
sudo service nginx restart
```

## 設定ファイル
``` sh
sudo touch /etc/nginx/conf.d/receipt-scanner-production.conf
sudo nano /etc/nginx/conf.d/receipt-scanner-production.conf
```

設定ファイル内容
```
    listen 80;
    server_name {EC2のIPアドレス};
    client_max_body_size 10g;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

テストして、リスタート
```
sudo nginx -t
sudo systemctl restart nginx
```

**Comment by ogaogs** [comment]
EC2にnextとpythonをrsyncで同期させ、実行して、取得したドメインを使ってアクセスしようと思っていますがうまくいっていません。やったことをいかにまとめています。

EC2にsshで接続。PosgresとPythonとNextが動く環境を整備。
NextとPythonを実行。PostgresはRDSで起動済み。
EC2にElasticIPアドレスをつけた。

お名前.comでogaogaoga.comというドメインを取得。awsのRoute53でogaogaoga.comでホストゾーンの作成。レコードを追加し、valueにEC2に紐づいたElasticIPアドレスを記入。レコードのサブドメインはreceipt-scanner。
ホストゾーンで作成された4つのNSレコードを最後の.を除いて、お名前.comで取得したドメインのネームサーバー情報に登録。

セキュリティーグループ

**Comment by ogaogs** [comment]
https://zenn.dev/aew2sbee/articles/aws-ec2-vscode

これに沿って、vscodeからssh接続した

**Comment by ogaogs** [comment]
## nextのrsync
ローカル
``` sh
rsync -avz --delete --exclude="prisma/migrations" -e "ssh -i /Users/ayumu/.ssh/aws/receipt-scanner-keypair.id_rsa" ./.next ./prisma ./.env ./package-lock.json ./package.json ./public ubuntu@3.114.8.20:/home/ubuntu/next
```

リモート
``` sh
prismaのseedingをするために、以下を実行した

npx prisma migrate deploy

npx prisma db seed
```

**Comment by ogaogs** [comment]
npm installした際にCPUが100%になってインスタンスが落ちてしまう。

![スクリーンショット 2024-10-27 4 59 44](https://github.com/user-attachments/assets/84b71f9f-c998-4745-93fb-94e69dae6e8c)

**Comment by ogaogs** [comment]
CPUをもうちょっとあげたほうがいい。

#5

**Comment by ogaogs** [comment]
Google CloudのAuthのcallbackを変える。

http://receipt-scanner.ogaogaoga.com/api/auth/callback/google

**Comment by ogaogs** [comment]
## pythonのrysync
ローカル
``` sh
rsync -avz --delete -e "ssh -i /Users/ayumu/.ssh/aws/receipt-scanner-keypair.id_rsa" ./api ./src ./.venv ./.python-version ./pyproject.toml ./requirements-dev.lock ./requirements.lock ./README.md  ubuntu@<ElasticIP>:/home/ubuntu/python
```

rye のインストール
``` sh
curl -sSf https://rye.astral.sh/get | bash
echo 'source "$HOME/.rye/env"' >> ~/.profile
```

tesseractのインストール
``` sh
sudo apt -y update
sudo apt -y install tesseract-ocr
```

~~pipのインストールとopencv-headlessのインストール(pipインストールするなら、ryeいらない。)~~
``` sh
sudo apt install python3-pip
pip install opencv-python-headless
```

libGL.so.1のインストール
``` sh
sudo apt update
sudo apt install libgl1-mesa-glx
```

OPENAI_API_KEYの設定
``` sh
export OPENAI_API_KEY="OPENAI_API_KEY"
```

**Comment by ogaogs** [comment]
receipt-scanner.ogaogaoga.comにアクセスしてもnginxしか返ってこない。

nginx 周りのログ
``` sh
systemctl status nginx
```

**Comment by ogaogs** [comment]
以下のように変更

``` conf
 server {
        listen       80;
        listen       [::]:80;
        server_name  3.114.8.20;

        location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade; 
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        }
    }
```

**Comment by ogaogs** [comment]
```
  GNU nano 6.2                                      /etc/nginx/conf.d/receipt-scanner-production.conf                                               
 server {
        listen       80;
        listen       [::]:80;
        server_name  receipt-scanner.ogaogaoga.com;

        location / {
        proxy_pass http://localhost;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        }
    }
```

sudo tail -f /var/log/nginx/error.log
```
2024/10/27 05:01:13 [alert] 21376#21376: *1179 768 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: receipt-scanner.ogaogaoga.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "receipt-scanner.ogaogaoga.com"
```

**Comment by ogaogs** [comment]
3000番は空いてる
```
ubuntu@ip-10-0-0-122:~/next$ netstat -atn | grep LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:33945         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::3000                 :::*                    LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN    
```

でけど、localhostじゃないんか？

**Comment by ogaogs** [comment]
http://3.114.8.20にはアクセスできる。

http://localhost:3000にもアクセスできる

どちらも家計簿アプリが出てくる

**Comment by ogaogs** [comment]
ここのservernameを変えるとngixxにもアクセスできなくなるため、ここはあっている。

``` 
 server {
        listen       80;
        listen       [::]:80;
        server_name  3.14.8.20;
```

**Comment by ogaogs** [comment]
```
ubuntu@ip-10-0-0-122:/var/log/nginx$ sudo tail -f access.log
119.106.21.95 - - [27/Oct/2024:08:13:12 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
119.106.21.95 - - [27/Oct/2024:08:13:40 +0000] "GET / HTTP/1.1" 200 396 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
122.117.95.52 - - [27/Oct/2024:08:37:50 +0000] "GET / HTTP/1.0" 200 612 "-" "Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
43.129.169.161 - - [27/Oct/2024:08:47:18 +0000] "HEAD /Core/Skin/Login.aspx HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
93.123.85.155 - - [27/Oct/2024:09:03:11 +0000] "GET /.env HTTP/1.1" 404 197 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
93.123.85.155 - - [27/Oct/2024:09:03:12 +0000] "POST / HTTP/1.1" 405 568 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
119.106.21.95 - - [27/Oct/2024:09:10:57 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
119.106.21.95 - - [27/Oct/2024:09:10:57 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
119.106.21.95 - - [27/Oct/2024:09:10:58 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
119.106.21.95 - - [27/Oct/2024:09:10:58 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
```

**Comment by ogaogs** [comment]
ハードリロードした場合

```
119.106.21.95 - - [27/Oct/2024:09:14:25 +0000] "GET / HTTP/1.1" 200 396 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
```

**Comment by ogaogs** [comment]
https://patrickjamesoneill.medium.com/404-not-found-with-docker-react-router-and-nginx-21fdce02c5

> The problem was my in my nginx.conf file I had a line:
>
 > include /etc/nginx/conf.d/*.conf;
> This was telling it to include the default config files which seemed to be overwriting my own. Commenting out or > deleting this line then building and running the images meant the end of the 404 errors.

`/etc/nginx/nginx.conf`に`include /etc/nginx/conf.d/*.conf;`を入れていたことから、confファイルが上書きされていて、うまく反映されていなかった。
よって、これを削除した。

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        server {
            listen       80;
            listen       [::]:80;
            server_name  receipt-scanner.ogaogaoga.com;

            location / {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
        }
  }
 }

#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}
```

すると、http://receipt-scanner.ogaogaoga.com/ にアクセスした際にログインページが表示されるようになった

**Comment by ogaogs** [comment]
## pm2のコマンド

アプリの実行
`pm2 start npm --name "your-app-name" -- start -- --port 3000`

アプリの停止
`pm2 stop app1`

アプリ一覧
`pm2 list`

アプリのログを見るコマンド
`pm2 logs app-name`

**Comment by corrosive4354** [comment]
あなたの方法は面倒すぎます。node.jsとPSQLを使用しているため、ワンクリックでデプロイできる[Servbay](servbay.com)を直接使用できます。

**Comment by ogaogs** [comment]
sevbayのご教授いただきありがとうございます。
一旦、docker を使ってやってみようと思います。

**Comment by ogaogs** [comment]
nextのキャッシュ削除系のコマンド

https://qiita.com/gourmet-dev/items/f95105f76ed931711bd3

**Comment by ogaogs** [comment]
ec2を作成後にelasticipアドレスを作成
route53のrecipt-scannerのレコードにelasticipアドレスをつける

**Comment by ogaogs** [comment]
``` sh
## rsync後
mv .env.prod .env
npx prisma db push ## 途中でprisma installするか聞かれる
```

上記を実行後に以下を試みた。
```sh
npx prisma db seed
```

すると以下のエラーが出た
``` sh
Environment variables loaded from .env
Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...

An error occurred while running the seed command:
Error: Command failed with ENOENT: ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts
spawn ts-node ENOENT
```

以下を実行した。ts-nodeがなかったのが原因そう。
``` sh
npx ts-node prisma/seed.ts
```

すると以下のようにfacker.jsがないエラーが出た。でもこれ、ビルドしたイメージに入ってないの？
``` sh
~/receipt_scanner/next_app$ npx ts-node prisma/seed.ts
Need to install the following packages:
ts-node@10.9.2
Ok to proceed? (y) y

/home/ubuntu/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
prisma/seed.ts:2:23 - error TS2307: Cannot find module '@faker-js/faker' or its corresponding type declarations.

2 import { faker } from "@faker-js/faker";
                        ~~~~~~~~~~~~~~~~~

    at createTSError (/home/ubuntu/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/ubuntu/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/ubuntu/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/ubuntu/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/ubuntu/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
    at node:internal/modules/cjs/loader:1689:10
    at Object.require.extensions.<computed> [as .ts] (/home/ubuntu/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14) {
  diagnosticCodes: [ 2307 ]
}

```


node_modulesの下はなprismaしかなかった。
``` sh
~/receipt_scanner/next_app/node_modules$ ls
@prisma  prisma
```

## 結論
localからnode_modulesをrsyncすると`npx prisma db push`と`npx prisma db seed`で怒られなくなった。
``` sh
rsync -av --delete -e 'ssh -i /Users/~~~/.ssh/aws/receipt-scanner-keypair.id_rsa' node_modules ubuntu@ec2~~~.amazonaws.com:/home/ubuntu/receipt_scanner/next_app/
```

**Comment by ogaogs** [comment]
https://github.com/AyumuOgasawara/receipt-scanner-infra/issues/4#issuecomment-2506830717 の後に

``` sh
export HOSTNAME="0.0.0.0"
node standalone/server.js
```
を行った。うまく実行された。

しかし、http://receipt-scanner.ogaogaoga.com/ にアクセスしてもnginxしか見れない。
`/etc/nginx/nginx.conf`はhttps://github.com/AyumuOgasawara/receipt-scanner-infra/issues/4#issuecomment-2440068359 と同じように書いている。

`/etc/nginx/nginx.conf`はhttps://github.com/AyumuOgasawara/receipt-scanner-infra/issues/4#issuecomment-2440068359 と思ったら、`}`が一つ抜けていたことを`sudo nginx -t`で確認。`{`をつけたし、」再び実行。
``` sh
sudo nginx -t
sudo systemctl restart nginx
```

**Comment by AyumuOgasawara** [comment]
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ nohup --version
nohup (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering.
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ nohup node standalone/server.js
nohup: ignoring input and appending output to 'nohup.out'
^Cubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ nohup node standalone/server.js &
[1] 839
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ nohup: ignoring input and appending output to 'nohup.out'
exit
logout
Connection to ec2-13-114-195-93.ap-northeast-1.compute.amazonaws.com closed.
ayumu@AyumunoMacBook-Air:~|⇒  ssh -i /Users/ayumu/.ssh/aws/receipt-scanner-keypair.id_rsa ubuntu@ec2-13-114-195-93.ap-northeast-1.compute.amazonaws.com
Welcome to Ubuntu 22.04.5 LTS (GNU/Linux 6.8.0-1019-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

 System information as of Fri Nov 29 10:27:39 UTC 2024

  System load:  0.0               Processes:             113
  Usage of /:   49.0% of 7.57GB   Users logged in:       0
  Memory usage: 25%               IPv4 address for eth0: 10.0.0.172
  Swap usage:   0%

 * Ubuntu Pro delivers the most comprehensive open source security and
   compliance features.

   https://ubuntu.com/aws/pro

Expanded Security Maintenance for Applications is not enabled.

1 update can be applied immediately.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status

New release '24.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Fri Nov 29 10:22:33 2024 from 207.65.186.66
ubuntu@ip-10-0-0-172:~$ cd receipt_scanner/next_app/
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ ls
node_modules  nohup.out  package-lock.json  package.json  prisma  public  standalone
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ tail -f nohup.out
    at async Ar.loadEngine (/home/ubuntu/receipt_scanner/next_app/standalone/node_modules/@prisma/client/runtime/library.js:111:448)
    at async Ar.instantiateLibrary (/home/ubuntu/receipt_scanner/next_app/standalone/node_modules/@prisma/client/runtime/library.js:110:12599) {
  clientVersion: '5.21.1',
  errorCode: undefined
}
 ⨯ The requested resource isn't a valid image for /default.png received text/html; charset=utf-8
 ⨯ The requested resource isn't a valid image for /default.png received text/html; charset=utf-8
 ⨯ The requested resource isn't a valid image for /default.png received text/html; charset=utf-8
 ⨯ The requested resource isn't a valid image for /default.png received text/html; charset=utf-8
 ⨯ The requested resource isn't a valid image for /default.png received text/html; charset=utf-8
 ⨯ The requested resource isn't a valid image for /default.png received text/html; charset=utf-8
 ⨯ The requested resource isn't a valid image for /default.png received text/html; charset=utf-8
^C
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ jobs
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ ps x
    PID TTY      STAT   TIME COMMAND
    713 ?        Ss     0:00 /lib/systemd/systemd --user
    716 ?        S      0:00 (sd-pam)
    839 ?        Sl     0:02 next-server (v14.2.13)
    912 ?        S      0:00 sshd: ubuntu@pts/0
    913 pts/0    Ss     0:00 -bash
    931 pts/0    R+     0:00 ps x
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ kill 839
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$ ps x
    PID TTY      STAT   TIME COMMAND
    713 ?        Ss     0:00 /lib/systemd/systemd --user
    716 ?        S      0:00 (sd-pam)
    912 ?        S      0:00 sshd: ubuntu@pts/0
    913 pts/0    Ss     0:00 -bash
    933 pts/0    R+     0:00 ps x
ubuntu@ip-10-0-0-172:~/receipt_scanner/next_app$

**Comment by ogaogs** [comment]
``` sh
# backgroundで実行
nohup node standalone/server.js & 

## 実行しているディレクトリにログが出る
tail -f nohup.out

# プロセスリストを確認
ps x

# プロセスidを指定してプロセスを殺す
kill {process_id}
```
